// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_RUxx3je5Pz8DOYItm5wZ19ExVSNujBM',
    appId: '1:171871758415:web:1b6c5539d4ec384229623a',
    messagingSenderId: '171871758415',
    projectId: 'uberdriver-2941d',
    authDomain: 'uberdriver-2941d.firebaseapp.com',
    databaseURL: 'https://uberdriver-2941d-default-rtdb.firebaseio.com',
    storageBucket: 'uberdriver-2941d.appspot.com',
    measurementId: 'G-DJ07PFFDQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBve_6PBeiO31bdWjP83owjPS3_K0loog',
    appId: '1:171871758415:android:9f4591fb6dcef3b929623a',
    messagingSenderId: '171871758415',
    projectId: 'uberdriver-2941d',
    databaseURL: 'https://uberdriver-2941d-default-rtdb.firebaseio.com',
    storageBucket: 'uberdriver-2941d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdRkt2qLyIRBKHJgcReRhadECokSGQFk4',
    appId: '1:171871758415:ios:c3579660852bee0529623a',
    messagingSenderId: '171871758415',
    projectId: 'uberdriver-2941d',
    databaseURL: 'https://uberdriver-2941d-default-rtdb.firebaseio.com',
    storageBucket: 'uberdriver-2941d.appspot.com',
    androidClientId:
        '171871758415-es04tgqjoduq5psa16uvudtbo9gik21a.apps.googleusercontent.com',
    iosClientId:
        '171871758415-usbuo6dk3tbcp4blio557lude8ptu83q.apps.googleusercontent.com',
    iosBundleId: 'com.example.ridewealthAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdRkt2qLyIRBKHJgcReRhadECokSGQFk4',
    appId: '1:171871758415:ios:c3579660852bee0529623a',
    messagingSenderId: '171871758415',
    projectId: 'uberdriver-2941d',
    databaseURL: 'https://uberdriver-2941d-default-rtdb.firebaseio.com',
    storageBucket: 'uberdriver-2941d.appspot.com',
    androidClientId:
        '171871758415-es04tgqjoduq5psa16uvudtbo9gik21a.apps.googleusercontent.com',
    iosClientId:
        '171871758415-usbuo6dk3tbcp4blio557lude8ptu83q.apps.googleusercontent.com',
    iosBundleId: 'com.example.ridewealthAssistant',
  );
}
